version: "3.7"

services:
    template:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: template
        restart: unless-stopped
        ports:
            - 3000:3000
