#!/usr/bin/env sh

error=0
cypress=$1
cypress_config=$2

$cypress verify || $cypress install

node __sapper__/build &
PID=$!

$cypress run --config-file "$cypress_config" || error=10

if [ "$error" -eq 0 ];then
    kill $PID
    exit 0
fi

exit $error
