name: compliance
on:
    pull_request:
        branches:
            - "*"
    push:
        branches:
            - "*"

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: dependencies
              run: make node_modules
            - name: lint
              run: make lint
            - name: build
              run: make build
            - name: test
              run: make test
            - name: build-image
              run: make docker
